version: 2

############################
# MODELS
############################

models:
  - name: int_campaigns
    description: Intermediate campaigns model at daily grain.

    tests:
      - dbt_utils.unique_combination_of_columns:
          arguments:
            combination_of_columns:
              - date
              - campaign_key

    columns:
      - name: date
        tests: [not_null]

      - name: paid_source
        tests: [not_null]

      - name: campaign_key
        tests: [not_null]

      - name: campaign_name

      - name: ads_cost
        tests: [not_null]

      - name: impression
      - name: click


############################
# SOURCES (TÜM PROJE)
############################

sources:
  # RAW DATA
  - name: raw
    tables:
      - name: sales
      - name: product
      - name: customer
      - name: ship

  # ADS DATA
  - name: ads
    tables:
      - name: adwords
      - name: bing
      - name: criteo
      - name: facebook
